services:
# === MCP ===
  mcp-yt-dlp:
    build: mcp
    container_name: mcp-yt-dlp
    ports:
      - "9000:8000"
    command: "--pass-environment --sse-port=8000 --sse-host 0.0.0.0 npx @kevinwatt/yt-dlp-mcp"
    volumes:
      - ./volumes/mcp/temp:/temp
    restart: unless-stopped
    networks:
      - chatbot-video

#  # Custom build MCP with FastAPI-MCP
#  mcp-weather:
#    build: ../app/mcp/weather
#    container_name: mcp-weather
#    environment:
#      - PYTHONUNBUFFERED=1
#    restart: unless-stopped
#    networks:
#      - llm-lab

# === Network ===
networks:
  chatbot-video:
    name: chatbot-video
    driver: bridge
